### PR TITLE
Reactsetup

### PR DESCRIPTION
**Pull request by rubyygrapefruit**

### CODE REVIEW

**Review by canderson22 — CHANGES_REQUESTED** [review]
Hey looking good @rubyygrapefruit but can I suggest using axios for ajax request instead of jQuery. I see you setup the axios for get companies twice one with jquery and one without in your App.jsx

**Comment by rubyygrapefruit** [comment]
Hey @canderson22 I changed my req to an aixos req :)

**Review by canderson22 — APPROVED** [review]
@rubyygrapefruit one more thing, ill approve it but just make you change it. On the axios request dont put localhost just put /people-also-bought

**Comment by rubyygrapefruit** [comment]
@canderson22  got it :) ill change it right now. thank youu!

**Pull request merged**
